### ISSUE TITLE
networkx library version uncompatible with python version

### ISSUE THREAD

**Issue by unautre** [jupyter/docker-stacks#1303]
Hello,

The library `networkx` that is installed in it (2.3) is too old to work with Python 3.9.
I guess it is installed as a dependency, because I couldn't find that library in the Dockerfile.

**What docker image you are using?**
**What complete docker command do you run to launch the container (omitting sensitive values)?**
I am using the `jupyter/scipy-notebook` image, with the default command.

**What steps do you take once the container is running to reproduce the issue?**
To reproduce the problem, create a Python 3 notebook, and in a cell, run the following code: `import networkx`

**What do you expect to happen?**
No error is thrown and the library is imported.

**What actually happens?**
When importing the module, the following error will be thrown:
```
ImportError: cannot import name 'gcd' from 'fractions' (/opt/conda/lib/python3.9/fractions.py)
```

** What could be done to fix the problem ?**
A workaround is to run a cell with the following command: `!pip install networkx==2.5`
The real solution is to fix the `networkx` version to 2.5 in the Dockerfile.

**Comment by jakob-keller** [comment]
I can confirm your report. networkx is indeed installed as a dependency of scikit-image. The current jupyter/scipy-notebook image includes version 2.3 which is incompatible with Python 3.9.

However, when digging into current build logs, it appears as if networkx==2.5.* is now being picked up automatically and there is no need for any changes to this project. Please be patient and wait for the next release to become available on Docker Hub, which should be very soon.

**Comment by jakob-keller** [comment]
@unautre: The latest [jupyter/scipy-notebook](https://hub.docker.com/r/jupyter/scipy-notebook) image includes networkx 2.5. This fixes your issue with importing in Python 3.9. Enjoy!

**Comment by mathbunnyru** [comment]
I think this issue can be closed then.
I checked - the latest version of the image effectively has networkx 2.5, which should work just fine.
